### ISSUE TITLE
What should be the rules of the "RepPointsServer"?

### ISSUE THREAD

**Issue by serapath** [wizardamigosinstitute/RepPointsServer#1]
We already started discussing in the [wizard chat](https://gitter.im/wizardamigosinstitute/chat) but we kind of need to come to an agreement about the "initial set of rules" with which we start the "RepPointsServer" or how the first implementation of the "RepPointsServer" should actually look like :-)

From then on, we can "vote" on commits to change the "RepPointsServer" and we deploy new versions.
The "RepPointsServer" will basically manage the stuff in the "data folder" :-)

**Comment by Nasdneb** [comment]
I'm happy with the rules how they are currently.
I would like to have badges/tags for each user to see what they did and currently do

**Comment by Nasdneb** [comment]
Also I would like to try a voting system based on the rep. points

**Comment by Nasdneb** [comment]
And who wants to do a little frontend? The frontend should feature:
- list of all users with points
- transfer points to a user

Nice to have would be:
- show current rules

**Comment by serapath** [comment]
i would actually try to do such a thing :-)
I just think - the rules might not yet be clear to all of us and even to me they are not clear.

#### I understand we have:
- a "Point Creation Rate"
- a "Redistribution Rate"
- an account for each participant that states her/his current amount of "Reputation Points"

#### It's unclear to me how:
- we vote on the "Point Creation Rate" (I would suggest picking the median vote)
- we vote on the "Redistribution Rate" (I would suggest picking the median vote)

#### Beside that:

It's not clear with how many points we start, we could just start with the same amont of points (e.g. 10 points), but imagine we would not have 5 but 100 participants right now - if what we try was more popular and already proven to work, then a hand full of people who worked already some time to make it happen would basically share with all those new participants who would, at least in the beginning, be "free riders"

I think in the chat i tried to write down what has been done so far - which doesn't mean that there has to be points now equal to the work that has already been invested, but it would be nice to hear everyone's opinion on that to start with something that everyone would feel ok with.

**Comment by serapath** [comment]
@ninabreznik @derhuerst @vysogot @Nasdneb 

> https://github.com/wizardamigosinstitute/RepPointsServer/blob/master/rules.js
> https://github.com/wizardamigosinstitute/RepPointsServer/blob/master/dis_snapshot.js
> We might need to brainstorm how we can change rules in the future and how we start with points, e.g. Nina and Myself started the wizard school in April/May this year, teached kids, created website + texts + logos, went around with lots of flyers and invested some energy into social media (twitter/facebook/blog/....) and even paid for domains, flyers, logo design on fiver.de
> 
> then Yannis helped with a little re-design of the website and was brainstorming with us.
> With Alexej we know were co-organizing the CodeMotion Event and we built some marketing materials and concepts for activities we could do with kids + we brainstormed about how we could do the shares or co-ownership. Alexej now created a repository for the server (see above)
> So maybe we should write those things down in a structured way and think about how to evaluate them when we give each other those "Reputation Points"  It would be great if we could continue discussion about it here:
> https://github.com/wizardamigosinstitute/RepPointsServer/issues Just someone create an issue and we start brainstorming about the topic there

@all what do we do with that?
@all what should be the initial "rates" mentioned above - in case you agree all with the general mechanics - and if there are questions, please feel free to ask them or make suggestions how to improve them :-)

**Comment by vysogot** [comment]
Lets start with flat rate, each has 10 points. Now there is a wall where columns are named by each member and below their name a list of what they did and if they did something together the items should be linked. So anyone can go to a "What's done" wall and click +1 if they think the action was valuable. This way we transfer our points, so you give +1 but you get -1. If the item was done by many, the point divides itself evenly (into a float). Next case. When you have 0 points left you get the basic minimal income but you should be concerned that maybe you are a parricide. People will support you and lend a hand but to gain respect (or a point) you actually have to do something yourself. Now the thing is that there is a total income. From the total, before evaluation we subtract the costs like materials and rents. I wouldn't evaluate "the hours spend on brainstorming" cause with this layer of abstraction it will be difficult to manage it altogether. But! If somebody came up with a great idea during the brainstorm then people should point it out and then he can put on the wall under his name: "I came up with the idea of the algorithm/event/game/video ABC" and then people will rate it by giving him/her points. But no fluffy data, just concrete. So then once a week or a month or some given period of time that will based on the actual activity which now we cannot predict, the rates get gradually flattened. Someone with 20 points now has 18, the guy with 0 now has 1 or 2. The points get flattened straight after the money evaluation. (I just edited it). Aha, now I noticed it - respect points I mentioned = your reputation points. That's my first idea about it.

**Comment by Nasdneb** [comment]
yes, I like the idea to put points only on activites

**Comment by Nasdneb** [comment]
I would also say lets start with 10 points each. Then everyone makes his list of activities, and we can distribute our points.

For the redistribution and creation of points, I suggest a higher rate for the beginning, so we can see how the game works. My suggestion:
- Redistribution: Redistribute 5% each day
- Creation: Create 10 new points each week

**Comment by vysogot** [comment]
What is the use of creating new points each week?

**Comment by serapath** [comment]
**The `Reputation Points` work a bit like shares in a company. I can try to explain the meaning of the Redistribution Rate and Creation Rate. You need a way to create new shares and a Creation Rate is one way of creating new shares. You need a Redistribution Rate, which is meant to be a price to pay for having shares and others respecting that, so maybe the rates should be renamed to reflect their meaning better**

I think, all the rules (they are technical), should be explained, so that their meaning or the reasons behind become understandable. Below I'll try to give my understanding.

#### Creation Rate [`CR`] is "inflationary" + enables an increased resolution

It "waters down" the work or effort that was already put into building the organization (in our case: wizard amigos institute), so if somebody new comes and didn't do anything yet, he will get points "for free" and thus earn money every time revenue comes in.

_For example, somebody **A** could work 40 hours in one week on a job or client project and earn money, while someone else **B** spends 40 hours in one week organizing an event, doing a lot of stuff for no money and earns some points for it. Then 2 weeks later, in response to the event some parents/kids come and ask to actually join and take some free lessons and 2 or 3 weeks later, they actually take a paid lesson. Because of a "RR" of for example 5% and a "CR" of for example 10 points per week, A and B will earn some revenue, and maybe B will earn just a bit more then A who had the income from his regular work and didn't need to spend any time to make it happen. If **B** wouldnt have organized and given the lessons for free, there would be **no revenue** to be shared. Everyone could just think of her/his own ass and do a normal job instead to earn something._

#### Redistribution Rate [`RR`] is "inflationary" with keeping the resolution stable

It essentially has the same effect as the **CR**, but you do not need to calculate how many percentage of overall ownership you "lost". With the `CR` you need to divide your amount of points by the sum of all of points everyone has in order to see what your points mean. With `RR` you can just watch your points, because the overall number of points doesnt change.

**Comment by serapath** [comment]
Great :-) So we have one proposal already. I will also think about a proposal, but I already like the one from alexej.

@Nasdneb - if I understand correct, you say:
**1.** Everyone starts with 10 points
**2.** Redistribution: Redistribute 5% each day  
- `Reasoning`: To have fast impact that helps to get a feeling for the mechanics, thus "how it works")  

**3.** Creation: Create 10 new points each week
**4.** Then everyone makes his list of activities, and we can distribute our points. (i guess the 10 points)

**Comment by serapath** [comment]
@vysogot

###### Rules
- start with flatrate
- everyone gets 10 points
- only if you have 0 points you will get a UBI (Unconditional Basic Income)
- When there is "income", all "organization costs" (e.g. materials, rents, ...) are substracted, then distribution starts.
- brainstorming doesnt count as "organization costs" and not as "activity"
- "good ideas" from brainstorming can count as "activity" (e.g. algorithm/event/game/video ABC)
- renaming "reputation points" to "respect points"
  ###### App
- named column for each person
- below a list of tasks/activities that were accomplished
- items are linked if done together with others
- button where everyone can click to spend points to a certain activity
  - if done by many, it's distributed evenly about all contributors

What I did not understand is:

> So then once a week or a month or some given period of time that will based on the actual activity which now we cannot predict, the rates get gradually flattened. Someone with 20 points now has 18, the guy with 0 now has 1 or 2. The points get flattened straight after the money evaluation.

**Comment by vysogot** [comment]
I meant this case (let's imagine the UBI = 50 and we don't add new points):

End of period 1: 

```
points_distribution: { person1: 18, person2: 12:, person3: 8, person4: 2},
income: 1200, costs: 600, savings: 200, revenue: 400, 

// pay = UBI + personPoints/totalPoints * revenue
pays: { person1: 50 + (18/(18+12+8+2))*400, person2: 50 + (12/40)*400, person3: 50 + 80, person4: 70 }
```

Money gets transferred, paper work done
Time for redistribution (let's imagine no points were given to anyone by anyone but money came in)
10 is the centre of balance. Max is 20 and min is 0. We add or subtract 1 point per period

End of period 2: 

```
points_distribution: { person1: 17, person2: 11:, person3: 9, person4: 3},
income: 2000, costs: 1000, savings: 400, revenue: 600, 
pays: { person1: 50 + (17/(17+11+9+3)*600, person2: 50 + (11/40)*600, person3: 50 + 135, person4: 95 }
```

This way if nobody does any work and no points gets transferred then after maximum 10 redistribution periods every one is on flat 10, 10, 10, 10 again.
If new person joins it gets 10 points to start with.
It should be obligatory to vote for activities (making points rotate)
I introduced a maximum so that there is no capital competition.

That's a fresh open thought, let me know which parts of it you resonate with.

**Comment by Nasdneb** [comment]
@vysogot You introduce an explicit, fixed UBI. Maybe this is also something nice to think about.

The idea in the first place was to have an implicit UBI, that comes from redistribution and creation of points. This way we could avoid voting all the time on how big the UBI should be.

**Comment by vysogot** [comment]
How about:

```
UBI = revenue * 33% / number of people
surplus = revenue - UBI
pay = UBI + personPoints/totalPoints*surplus
```

**Comment by Nasdneb** [comment]
I like that. @serapath what do you think about it?

**Comment by serapath** [comment]
I think we should use the official vocabulary of financial accounting, thus:
- **Revenue** (instead of income)
- **Savings** (is an illusion, but maybe you mean money on the bank account)
- **Costs** (could be invoices by us working for our institute or something else)
- **Dividend** (what you named "revenue" - is paying owners money)

Would be great to come up with standard way of writing down what's happening, thus:
- **Balance Sheet** in double entry book keeping has two columns.
  - **Activa** (left side) - shows all the assets of a company
  - **Passiva** (right side) - shows who gave the ressources (e.g. bank loans, owners/shareholders,...)

The activity over time happens in so called **accounting records** and a subset of those represents the **cash flow** which is what you were talking about:
- money coming in
- money going out

I started https://github.com/serapath/economy a long time ago - and maybe another time we can start brainstorming about that kind of stuff more in detail. I would be interested, but for now i'd like to stay more focused on just a common vocabulary and everything we need to structure our "Reputation Points" :-)

**Comment by vysogot** [comment]
Very good. I'm bad with financial vocabulary and I appreciate this listing. By savings I meant that if there is any revenue 20% should go for the savings account from which we could make investments. Some hot cash if needed for a project or to sponsor something. By costs I meant things like rents or paper, pens, toys or boards, server etc.

**Comment by serapath** [comment]
Otherwise...
1. For me, the **Redistribution Rate** and to some degree also the **Creation Rate** already cover the **UBI** and I wouldnt want to introduce some artificial fixed value that we might vote on. it just makes everything more complex.
2. I also do not like or at least am not sure what is the value in having a **maximum** for how many coins someone can have.
3. I was thinking about whether it should be obligatory to vote or not and i agree that somebody who doesnt vote - especially if that becomes a habit - causes a lot of problems, but what to do about it? I'm against forcing but all for rewards to those who actually vote

##### Again...

There needs to be a high motivation for people to actually earn the cake that we want to distribute.
If the "creation rate" and "redistribution rate" is too high and new people come in (actually i would like to not have a rule to exclude people - whoever joins joins and can never be kicked out.)
If people don't like the people in, they have to leave and start a new thing instead - so everything should be set up in a way, that such a split (or better **fork**) is easy.

##### Questions

For me, before I maybe come up with my own suggestions (i'm not sure yet), i have a question.
Why would i ever **vote** for an activity of others, if i spend votes that would otherwise give me revenue... i don't feel like motivated to vote a lot - i guess i would be rather lazy or only vote as much as the person that gives the least amount of votes

**Comment by serapath** [comment]
@vysogot 
No problem. I guess you meant that. I would rather have no savings, but every proposal to invest money could be listed and then everyone can spend on it - so "savings" are done by everyone personally instead

**Comment by vysogot** [comment]
I encourage obligatory voting in a community that one joins voluntarily. It is beneficial because people get used to be actively responsible. It also enforces the points rotation. When it comes to motivation I wouldn't count on money. Mission itself and the team goals should be the main drive behind the action. Money is an important outcome. Priorities must be clear otherwise we start to make a regular profit oriented company with personal financial pursuits. For the same reason I would keep a non-personal savings strategy. I also agree that people should not get kicked out easily. But if somebody brings damage and is not willing to change there should be a policy to let him go find his place somewhere else.

**Comment by serapath** [comment]
I'm against enforcement, only rewards.
If just one person participates in "voting", that person directs everything until others decide to participate. For doing the voting, a person should be rewarded.
I really dislike any kind of "enforcement".
If somebody **[A]** works/behaves in a way somebody **[B]** dislikes, than **B** should leave and either do something else or make a _fork_ and then continue on his/her own and ask others if they want to join the new thing.

So everyone who feels - as you say - _mission itself and the team goals_ - leads and directs and others follow. For leading, the person is rewarded "Reputation Points". I don't believe it's possible to prevent some people starting to follow _"personal financial pursuits"_, so the rules need to be able to cope with that.
Also the "non-personal-savings" strategy - I believe there should be as little rules as possible and whoever makes rules is free to live according to them - so for example you can not have any personal savings if you wish - but I dont think those policies should be forced on others

**Comment by vysogot** [comment]
Ok, that's fine.

**Comment by serapath** [comment]
I close this issue for now.
I tried to summarize everything said here in the issue https://github.com/wizardamigosinstitute/RepPointsServer/issues/6
If I missed something, please feel free to add it to the new issue.

**UPDATE:**
The latest updates are to be found here: https://github.com/wizardamigosinstitute/RepPointsServer/pull/9
