### ISSUE TITLE
implement github api

### ISSUE THREAD

**Issue by Nasdneb** [wizardamigosinstitute/RepPointsServer#3]

**Comment by ninabreznik** [comment]
What will we use for backend (if anything - meaning Github as a backend :))? Do we want to go with Node or we do Rails backend and JS frontend?

**Comment by Nasdneb** [comment]
So far, the backend is developed in Node.js. We are currently using Github as database, history and communication tool

**Comment by ninabreznik** [comment]
Super. Sounds great!

**Comment by serapath** [comment]
**UPDATE:**
The latest updates are to be found here: https://github.com/wizardamigosinstitute/RepPointsServer/pull/9
