### ISSUE TITLE
develop first frontend prototype

### ISSUE THREAD

**Issue by Nasdneb** [wizardamigosinstitute/RepPointsServer#4]

**Comment by serapath** [comment]
Here we should once in Co Up sit down and on paper sketch all the features we need.
This should be done after we agreed on the "methodology" of how to manage the organization :-)

... once we have agreement on that, I would be up for implementing the frontend.
I would also assume the backend (and the communication with the github API) would need to be refined and/or adapted based on what we agree on.

**Comment by ninabreznik** [comment]
Agree, I think once it's clear what features we need, we can sketch the UX for the frontend.

**Comment by Nasdneb** [comment]
Ok, I would suggest a meeting to finish the currently open proposals. What about friday 5pm?

**Comment by serapath** [comment]
+1

**Comment by ninabreznik** [comment]
Hey, let's meet at 17h then. 

I suggest we sum up all our thoughts and create a model MVP and then see what is still open around certain features/ideas and try to get to the new chapter.

Will be there around 17h. See you!

**Comment by ninabreznik** [comment]
And one more thing - at least for me, I really need to put down all the "problems" (scenarios) that we are trying to solve with these: creation rate, distribution rate etc. Just to list them all and then it is going to be easier to evaluate different solutions (i.e. creation rate)...

So, as far as I am concerned I would be happy to se:
- list of all the issues/problems/scenarios we try to solve (i.e. what if someone joins today and goes fully in, what if someone is in but doesn't really participate, what if someone does all the workshops and others not a single one, what if someone brings lots of new "customers"  and does also lots of workshops or none or...
- and then based on this list a MVP (minimum viable product - model) - how could the system work and then we can modify this one based on the problems listed above

**Comment by serapath** [comment]
You can make `Micro Proposals` for the `Frontend Application`, but before we need to find agreement about the basic concept. I tried to summarize everything in a file that goes to the repository through a **pull request** and from now on we can discuss in the pull requests instead of issues :-)

Added to SPECIFICATION/README.md in upcoming pull request -> please discuss it there.

I recommend to **`CLOSE`** this issue, @Nasdneb 

**UPDATE:**
The latest updates are to be found here: https://github.com/wizardamigosinstitute/RepPointsServer/pull/9

**Comment by serapath** [comment]
You can make `Micro Proposals` for the `Frontend Application`, but before we need to find agreement about the basic concept. I tried to summarize everything in a file that goes to the repository through a **pull request** and from now on we can discuss in the pull requests instead of issues :-)
